class CourtOrderTitle
  VALUES = %w[
    antisocial_behaviour_order
    application_for_costs_against_convicted_defendant
    bind_over
    bind_over_to_keep_the_peace
    breach_of_non_molestation_order
    cash_seizure_and_forfeiture_order
    civil_disclosure_order
    civil_recovery_order
    closure_notice_for_premesis
    confiscation_order
    criminal_antisocial_behaviour_order
    criminal_behaviour_order
    criminal_proceeds_of_crime_act_disclosure_orders
    deportation_of_foreign_national_prisoners
    deportation_order
    deprivation_of_property
    disclosure_notice_for_the_purpose_of_terrorist_investigations
    discretionary_driving_disqualification
    disqualification_from_working_with_children
    disruption_of_legal_professionals_facilitating_serious_organised_crime
    dog_control_order
    domestic_violence_protection_order
    enforcement_receivership_order
    european_arrest_warrant
    european_protection_order
    exclusion_order_licenced_premesis
    financial_reporting_order
    football_banning_order
    forced_marriage_protection_order
    forfeiture_and_destruction_of_dog_order
    forfeiture_and_destruction_of_drugs_order
    forfeiture_and_destruction_of_property
    forfeiture_and_destruction_of_weapon_order
    forfeiture_and_destruction_order
    forfeiture_of_indecent_photograph
    forfeiture_of_motor_vehicle_order
    forfeiture_of_obscene_publications
    immunity_agreements
    interim_receiving_order
    no_orders_required
    notification_requirements_sex_offender_register
    obligatory_driving_disqualification
    other
    parental_bind_order
    parenting_order
    property_freezing_order
    refusal_and_revocation_of_citizenship
    restitution_order
    restraining_order
    restraint_order
    restricted_use_publications
    revocation_of_a_pilots_licence
    sentence_discount_agreement
    serious_crime_prevention_order
    sexual_risk_order
    travel_restriction_order
    violent_offender_order
  ]

  attribute :value, String
  validates :value, inclusion: { in: VALUES }
end
